version: '3.1'
services:
  db:
    image: mysql
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: school
    volumes:
      - 'school:/var/lib/mysql'
volumes:
  school: null
